### ISSUE TITLE
Add an optional switch to connect to Azure AD using Connect-MSOLService

### ISSUE THREAD

**Issue by MasterofGhouls** [cgoosen/Connect-365#4]
While I agree that Connect-AzureAD is the future, there are some cases where Connect-MSOLService must be used for queries and changes in Azure AD.  Having it as an optional Service to connect to would be fantastic.

So having two Azure AD Service connection options is what I am requesting, maybe listing the second one as "Azure AD (MSOL)".

**Comment by cgoosen** [comment]
That makes sense - I find myself using MSOL occasionally myself and have thought about doing this. Thanks for the request - I'll see what I can do.

**Comment by cgoosen** [comment]
Added in V1.3
