### ISSUE TITLE
Exchange Online Module keeps failing prerequisite Check

### ISSUE THREAD

**Issue by AICDP-User** [cgoosen/Connect-365#5]
latest version of the module is installed, but keeps showing as failed in the prerequisite check.
What am i doing wrong?

**Comment by cgoosen** [comment]
Looks like a bug - if the module is installed correctly it should still connect. I'll take a look at fixing the issue.
Thanks for reporting.

**Comment by cgoosen** [comment]
Updated in ver 1.3.1
